### ISSUE TITLE
Something left

### ISSUE THREAD

**Issue by Jillorval** [kevindqc/mrrl#2]
When buying the item available with the cape today (Sinister pile of sand), I had 2 Smelly pile of gloop remaining.

**Comment by kevindqc** [comment]
Did you get any from chests using the scrying stone? I plan on adding an "Materials in inventory" section for something like that.

**Comment by Jillorval** [comment]
I got one of the 3 "strange" items (for Mardivas" laboratory), don't remember which one it was

**Comment by kevindqc** [comment]
The Pinky Cultist Finger wanted 5 smelly piles of gloop instead of 4, I fixed it. Thanks!
